# Generated by Django 5.2.8 on 2025-11-25 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='posted_Dated',
        ),
    ]
